config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'setup_account/index', to: 'setup_account#index'
  post 'setup_account/connect', to: 'setup_account#connect'
  post 'setup_account/calendar', to: 'setup_account#calendar'
  get 'welcome/index', to: 'welcome#index'

  resources :appointments, only: [:show, :update], param: :slug, path: :citas
  resources :account_profiles, only: [:index, :update]
  resources :legal_static, only: [:index], path: 'legal'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'}

  authenticated :user do
    root 'account_profiles#index', as: :authenticated_root
  end

  root 'welcome#index'
end

app/controllers/setup_account_controller.rb
class SetupAccountController < ApplicationController
  before_action :authenticate_user!
  layout 'unauthenticated'

  def index
    @app_id = Kloudless.configuration.app_id
    @scope = Kloudless.configuration.scope
  end

  def connect
    id, access_token = params_account
    updated_account = CreateAccount.add_remote(account, id, access_token)

    @calendars = Kloudless::Calendars.find_all(Kloudless::Account.new(updated_account.remote_id, updated_account.auth_token))
  rescue Kloudless::Error, CreateAccount::Error => e
    @error_message = e.message
  end

  def calendar
    calendar_id, calendar_name, calendar_timezone = params_calendar
    CreateAccount.add_calendar(account, calendar_id, calendar_name, calendar_timezone)

    redirect_to account_profiles_path(show_welcome_modal)
  end

  private

  def show_welcome_modal
    { welcome: 'true' }
  end

  def account
    current_user.account
  end

  def params_calendar
    params.require(:account).require(%i[calendar_id calendar_name calendar_timezone])
  end

  def params_account
    params.require(:account).require(%i[id access_token])
  end
end

app/views/setup_account/connect.html.erb
<div class="row">
  <div class="col-12 col-md-6 offset-md-3">
    <div class="card">
      <div class="card-header">
        <%= image_tag "home/logo.png", alt: 'Logo', class:'logo-card' %>
      </div>
      <div class="card-body">
        <% if(@error_message.nil?) %>
          <p>
            <%= I18n.t('views.setup_account.connect.text') %>
          </p>
          <%= form_with scope: :account, url: setup_account_calendar_path, local: true, data: { controller: 'select_calendar'} do |f| %>
            <%= hidden_field 'account', 'calendar_name', data: { target: 'select_calendar.name' }  %>
            <%= hidden_field 'account', 'calendar_timezone', data: { target: 'select_calendar.timezone' }  %>
            <%= f.collection_radio_buttons :calendar_id, @calendars, :id, :name, checked: @calendars&.first&.id do |b| %>
              <div class="form-check">
                <%= b.radio_button class: "form-check-input", data: { name: b.text, timezone: b.object.timezone } %>
                <%= b.label class: 'form-check-label' %>
              </div>
            <% end %>
            <div class="row">
              <%= f.submit I18n.t('views.setup_account.connect.submit'), class: "col-12 col-sm-6 offset-sm-3 btn btn-block btn-primary mt-3", data: {action: "select_calendar#submit" } %>
            </div>
          <% end %>
        <% else %>
          <div class="alert alert-danger">Ha ocurrido un error. Pongase en contacto con soporte técnico. <%= @error_message %> </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/setup_account/index.html.erb
<div class="row">
  <div class="col-12 col-md-6 offset-md-3">
    <div class="card">
      <div class="card-header">
        <%= image_tag "home/logo.png", alt: 'Logo', class:'logo-card' %>
      </div>
      <div class="card-body">
        <p class="h5">
          <%= t('views.setup_account.index.text_1') %>
        </p>
        <div class="row mt-3">
          <div class="col text-center">
            <%= image_tag "setup_account/google_calendar.png", alt: 'google calendar' %>
            <small>Google Calendar</small>
          </div>
          <div class="col text-center">
            <%= image_tag "setup_account/outlook_calendar.png", alt: 'outlook calendar' %>
            <small>Outlook Calendar</small>
          </div>
          <div class="col text-center">
            <%= image_tag "setup_account/exchange.png", alt: 'exchange' %>
            <small>Exchange Server</small>
          </div>
          <div class="col text-center">
            <%= image_tag "setup_account/other.png", alt: 'caldav' %>
            <small>CalDAV(*)</small>
          </div>
        </div>

        <p class="mt-3">
          <%= t('views.setup_account.index.caldav') %>
        </p>

        <%= form_with scope: :account, url: setup_account_connect_url, locale:true, data: { 'controller' => 'connect', 'connect-appid' => @app_id, 'connect-scope' => @scope } do |f| %>
          <%= hidden_field 'account', 'id', data: { target: 'connect.id' } %>
          <%= hidden_field 'account', 'access_token', data: { target: 'connect.accessToken' } %>

          <div class="row">
            <div id="auth-error" class="alert alert-danger d-none">Ha ocurrido un error conectando el calendario. Vuelva a intentarlo y pongase en contacto con soporte técnico si el error persiste.</div>
          </div>
          <div class="row">
            <%= f.submit t('views.setup_account.index.submit'), class: "col-12 col-sm-6 offset-sm-3 btn btn-block btn-primary mt-3", data: {action: "connect#auth"} %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>