config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'setup_account/index', to: 'setup_account#index'
  post 'setup_account/connect', to: 'setup_account#connect'
  post 'setup_account/calendar', to: 'setup_account#calendar'
  get 'welcome/index', to: 'welcome#index'

  resources :appointments, only: [:show, :update], param: :slug, path: :citas
  resources :account_profiles, only: [:index, :update]
  resources :legal_static, only: [:index], path: 'legal'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'}

  authenticated :user do
    root 'account_profiles#index', as: :authenticated_root
  end

  root 'welcome#index'
end

app/controllers/account_profiles_controller.rb
class AccountProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :account_present!

  def index
    periods = AvailablePeriodForm.from_models(AvailablePeriod.find_by_account(account))

    periods_table_data(periods)
    links_data
    hide_alerts
  end

  def update
    periods = UpdateAvailablePeriods.call(account, periods_params)
    update_settings

    periods_table_data(periods)
    links_data
    show_alerts(periods)

    respond_to do |format|
      format.html { render :index }
      format.js
    end
  end

  private

  def show_alerts(periods)
    @success = periods.all? { |p| p.errors.empty? } && @account_settings.valid?
    @error = !@success
  end

  def hide_alerts
    @success = nil
    @error = nil
  end

  def update_settings
    account.account_setting.update_form_settings(duration_params[:minutes].to_i, address_params[:address])
  end

  def duration_params
    params.require(:duration).permit(:minutes)
  end

  def address_params
    params.permit(:address)
  end

  def periods_params
    params.require(:periods)
  end

  def links_data
    @form_url = appointment_url(account.account_setting.slug, host: t('host'))
  end

  def periods_table_data(periods)
    @account_id = account.id
    @periods = periods + missing_periods(periods)
    @account_settings = account.account_setting
  end

  def missing_periods(periods)
    days_saved = periods.map(&:day_of_week)
    days_missing = (1..7).to_a - days_saved

    days_missing.map do |d|
      AvailablePeriodForm.new.tap { |ap| ap.day_of_week = d }
    end
  end

  def account
    current_user.account
  end

  def account_present!
    redirect_to setup_account_index_path unless account.connected?
  end
end

app/views/account_profiles/_address.html.erb
<div class="form-group row">
  <label class="col-md-5 col-form-label" for="address"><%= I18n.t('views.account_profiles.index.address_label') %></label>
  <div class="col-md-7">
    <%= text_field_tag('address', @account_settings.address, add_error_attrs(@account_settings, [:address], {class: 'form-control'})) %>
  </div>
</div>

app/views/account_profiles/_duration.html.erb
<div class="form-group row">
  <label class="col-md-9 col-form-label" for="duration[minutes]"><%= I18n.t('views.account_profiles.index.duration_label') %></label>
  <div class="col-md-3">
    <%= number_field_tag('duration[minutes]', @account_settings.duration, add_error_attrs(@account_settings, [:duration], {class: 'form-control', placeholder: AccountSetting::DEFAULT_DURATION, min: AccountSetting::MIN_DURATION})) %>
  </div>
</div>

app/views/account_profiles/_periods_table.html.erb
<%= render partial: 'duration' %>
<%= render partial: 'address' %>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th style="width: 30%"><%= I18n.t('views.account_profiles.index.from') %></th>
        <th style="width: 30%"><%= I18n.t('views.account_profiles.index.to') %></th>
      </tr>
    </thead>
    <tbody>
      <% (1..7).each do |day| %>
        <% e = @periods.find { |p| p.day_of_week == day } %>
        <tr>
          <td class="align-middle">
            <div class='checkbox form-check'>
              <%= check_box_tag("periods[#{e.day_of_week}]", e.day_of_week, e.end_time.present?, class: 'form-check-input') %>
              <%= label_tag(e.day_of_week, t('date.day_names')[e.day_of_week % 7] ) %>
            </div>
          </td>
          <td>
            <%= text_field_tag("periods[start_#{e.day_of_week}]", e.start_time, add_error_attrs(e, [:start_time, :start_hour, :start_minute], {class: "form-control", disabled: e.start_time.blank?})) %>
          </td>
          <td>
            <%= text_field_tag("periods[end_#{e.day_of_week}]", e.end_time, add_error_attrs(e, [:end_time, :end_hour, :end_minute], {class: "form-control", disabled: e.end_time.blank?})) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if @success %>
    <div class="alert alert-success" role="alert"><%= I18n.t('views.account_profiles.index.success') %></div>
  <% end %>
  <% if @error %>
    <div class="alert alert-danger" role="alert"><%= I18n.t('views.account_profiles.index.error') %></div>
  <% end %>
</div>

app/views/account_profiles/_welcome_modal.html.erb
<div class="modal fade" id="welcome-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header landing">
        <div class="container-fluid">
          <div class="modal-title text-center mt-2">
            <%= image_tag "075-startup-70.png" %>
            <p class="h3">
              <%= I18n.t('views.account_profiles.index.modal_header') %>
            </p>
          </div>
        </div>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
          <p class="mt-3">
            <%= I18n.t('views.account_profiles.index.modal_introduction') %>
          </p>

          <div class="row">
            <div class="col-md-auto">
              <%= image_tag "home/023-distribution.png" %>
            </div>
            <div class="col-10">
              <%= raw t('views.account_profiles.index.modal_tip1') %>
            </div>
          </div>

          <div class="row mt-2">
            <div class="col-md-auto">
              <%= image_tag "065-schedule.png" %>
            </div>
            <div class="col-10">
              <%= raw t('views.account_profiles.index.modal_tip2') %>
            </div>
          </div>

          <div class="row mt-2">
            <div class="col-md-auto">
              <%= image_tag "home/045-paper-plane.png" %>
            </div>
            <div class="col-10">
              <%= raw t('views.account_profiles.index.modal_tip3') %>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" type="button" data-dismiss="modal"><%= t('views.account_profiles.index.modal_close') %></button>
      </div>
    </div>
  </div>
</div>

app/views/account_profiles/index.html.erb
<%= render 'welcome_modal' %>

<div data-controller="account-profiles">
  <div class="row">
    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-xl-4 offset-xl-4">
      <div class="card mt-2">
        <div class="card-header">
          <i class="fa fa-send-o"></i>
          <%= I18n.t('views.account_profiles.index.booking_header') %>
        </div>
        <div class="card-body">
          <div class="mx-center">
            <p>
            <%= I18n.t('views.account_profiles.index.booking_text') %>
            </p>
            <div class="alert alert-primary text-center"><%= @form_url %></div>
          </div>

          <div class="row">
            <button class="col-12 col-lg-8 offset-lg-2 col-xl-10 offset-xl-1 btn btn-primary" type="button" data-url="<%= @form_url %>" data-action="account-profiles#copy">
              <i class="fa fa-chain"></i>&nbsp;<%= I18n.t('views.account_profiles.index.copy_link') %>
            </button>
            <div id="clipboard-alert" class="mx-auto collapse text-success" role="alert"><%= I18n.t('views.account_profiles.index.copy_success') %></div>
          </div>
          <div class="row mt-2">
            <a href="whatsapp://send?text=Sigue este enlace para ver mi disponibilidad: <%= @form_url %>" class="col-12 col-lg-8 offset-lg-2 col-xl-10 offset-xl-1 btn btn-light">
              <i class="fa fa-whatsapp"></i>&nbsp;<%= I18n.t('views.account_profiles.index.share_whatsapp') %>
            </a>
          </div>
          <div class="row mt-2">
            <a href="<%= appointment_path(@account_settings.slug) %>" target="_blank" class="col-12 col-lg-8 offset-lg-2 col-xl-10 offset-xl-1 btn btn-light">
              <i class="fa fa-external-link"></i>&nbsp;<%= I18n.t('views.account_profiles.index.open_form') %>
            </a>
          </div>

        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-xl-4 offset-xl-4">
      <div class="card">
        <%= form_with url: account_profile_path(@account_id), method: :put do |f| %>
          <div class="card-header">
            <%= I18n.t('views.account_profiles.index.title') %>
          </div>

          <div id="periods-table" class="card-body">
            <%= render partial: 'periods_table' %>
          </div>

          <div class="card-footer">
            <%= button_tag 'Submit', class: "btn btn-primary btn-sm" do %>
              <i class="fa fa-dot-circle-o"></i>
              <%= I18n.t('views.account_profiles.index.save') %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/account_profiles/update.js.erb
$("#periods-table").html("<%= escape_javascript(render partial: 'periods_table' ) %>");