config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'setup_account/index', to: 'setup_account#index'
  post 'setup_account/connect', to: 'setup_account#connect'
  post 'setup_account/calendar', to: 'setup_account#calendar'
  get 'welcome/index', to: 'welcome#index'

  resources :appointments, only: [:show, :update], param: :slug, path: :citas
  resources :account_profiles, only: [:index, :update]
  resources :legal_static, only: [:index], path: 'legal'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'}

  authenticated :user do
    root 'account_profiles#index', as: :authenticated_root
  end

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout false
  def index; end
end

app/views/welcome/index.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>
    <html class="no-js lt-ie9 lt-ie8 lt-ie7">
<![endif]-->
<!--[if IE 7]>
    <html class="no-js lt-ie9 lt-ie8">
<![endif]-->
<!--[if IE 8]>
    <html class="no-js lt-ie9">
<![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en" class="js">
<!--<![endif]-->
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <title>Hora de Salir - Comparte espacios comunes fácilmente</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/x-icon" href="<%= image_url('favicon.ico') %>">
    <link rel="icon" type="image/x-icon" href="<%= image_url('favicon32x32.png') %>">
    <!--- End favicon-->

    <!-- build:css -->
      <!-- endbuild -->
    <!--End ALL STYLESHEET -->

  </head>

  <body>
    <div class="st_header_top">
      <div class="container">
        <div class="row">
        </div>
      </div>
    </div><div class="st_header-wrapper">
      <div id="stick-menu"></div>
      <header id="st-header-section" class="st_header_area st_header_btn p-t-b-none sticky-box-shadow">
        <div class="st_header_bottom bg-st-white">
          <div class="container">
            <div class="row">
              <div class="col-xl-2 col-lg-2 col-md-6 col-sm-6 col-xs-6 d-flex align-items-center">
                <div class="st_logo">
                  <%= image_tag "home/logo.png", alt: 'Logo' %>
                </div>
              </div>
              <div class="col-xl-10 col-lg-10 col-md-6 col-sm-6 col-xs-6 d-flex justify-content-end">
                <div class="st_nav_wrapper st_nav_wrapper_v2 st-mean-emerald text-right">
                  <div class="st_menu text-hover-emerald d-inline-block d-lg-inline-block d-md-none d-sm-none d-xs-none">
                    <ul>
                      <li class="m-l-r-none">
                        <%= link_to 'Inicia sesión', new_user_session_path, class:"st_default_btn sign_up st_plain_text text-emerald text-hover-emerald border-emerald" %>
                      </li>
                      <li class="m-l-r-none">
                        <%= link_to 'Conecta tu Calendario', new_user_registration_path, class:"st_default_btn sing_in bg-emerald bg-hover-st-aqua" %>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div><!--End row -->
          </div><!--End container -->
        </div>
      </header><!--End st_header_area -->
    </div>

    <section id="home" class="st_banner_area bg-polar margin-header" style="background-image: url(<%=image_path('home/banner-shape.png')%>);">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 d-flex justify-content-start align-items-center height-100vh-full-screen st-height-md-inherit">
            <div class="st_banner_waraper">
              <div class="st_banner_content color_black align_item">
                <h1 class="st-font-78 m-b-30 st-font-xs-48">Hora de Salir</h1>
                <h2 class="st-font-28 font-weight-light st-font-xs-28">Comparte espacios comunes fácilmente</h2>
                <%= link_to 'Conecta tu Calendario', new_user_registration_path, class:"st_default_btn text-capitalize bg-emerald bg-hover-st-aqua st_btn_large_shadow" %>
              </div>
            </div>
          </div>
          <div class="col-xl-5 offset-xl-1 col-lg-6 d-flex align-items-center justify-content-end height-100vh-full-screen st-height-md-inherit">
            <div class="st_banner_info_box align_item m-md-b-100">
              <div class="st_sidebar_single_item wow fadeInUp" data-wow-delay="0.3s">
                <div class="st_banner_sidebar_icon">
                  <%= image_tag "065-schedule.png" %>
                </div>
                <div class="st_banner_sidebar_content">
                  <h3>CONECTA TU CALENDARIO</h3>
                  <p>Decide las horas en que el espacio está disponible</p>
                </div>
              </div>
              <div class="st_sidebar_single_item wow fadeInUp" data-wow-delay="0.5s">
                <div class="st_banner_sidebar_icon">
                  <%= image_tag "home/045-paper-plane.png" %>
                </div>
                <div class="st_banner_sidebar_content">
                  <h3>COMPARTE UN ENLACE</h3>
                  <p>Envía fácilmente la disponibilidad del espacio a tus vecinos y redes de contactos</p>
                </div>
              </div>
              <div class="st_sidebar_single_item wow fadeInUp" data-wow-delay="0.7s">
                <div class="st_banner_sidebar_icon">
                  <%= image_tag "home/027-flag.png" %>
                </div>
                <div class="st_banner_sidebar_content">
                  <h3>RECIBE PETICIONES</h3>
                  <p>Ahórrate toneladas de correos y whatsapps organizándote con tus vecinos</p>
                </div>
              </div>
            </div>
          </div>
        </div><!--End row -->
      </div><!--End container -->
    </section><!--End st_banner_area -->

    <div class="st_feature_area st_section_padding p-b-80 p-sm-b-30">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="st_feature_item_wrapper p-t-30 text-center">
              <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                  <div class="st_feature_single_item wow fadeIn" data-wow-delay="0.6s">
                    <%= image_tag "065-schedule.png" %>
                    <h3>Integrado con tu calendario</h3>
                    <p>Funciona con Google, Outlook, Exchange Server y CalDAV.</p>
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                  <div class="st_feature_single_item wow fadeIn" data-wow-delay="0.5s">
                    <%= image_tag "home/072-smartphone.png" %>
                    <h3>Adaptado para móviles</h3>
                    <p>Funciona aunque no estés delante del ordenador.</p>
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                  <div class="st_feature_single_item wow fadeIn" data-wow-delay="0.3s">
                    <%= image_tag "home/023-distribution.png" %>
                    <h3>Fácil de configurar</h3>
                    <p>Indica las horas en que el espacio estará abierto, nosotros nos encargamos del resto.</p>
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                  <div class="st_feature_single_item wow fadeIn" data-wow-delay="0.4s">
                    <%= image_tag "home/009-team.png" %>
                    <h3>Por ciudadanos para ciudadanos</h3>
                    <p>Compartimos tus problemas, hemos hecho este software para nosotros pensando en ti</p>
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                  <div class="st_feature_single_item wow fadeIn" data-wow-delay="0.4s">
                    <%= image_tag "home/064-savings.png" %>
                    <h3>Ahorra tiempo</h3>
                    <p>Haz lo que más te apetezca ahora que no tienes que responder mensajes coordinando las visitas</p>
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                  <div class="st_feature_single_item wow fadeIn" data-wow-delay="0.3s">
                    <%= image_tag "home/075-startup.png" %>
                    <h3>Alta en menos de 1 minuto</h3>
                    <p>Conecta el calendario, pon tu nombre y a funcionar.</p>
                  </div>
                </div>
              </div><!--End row -->
            </div>
          </div>
        </div><!--End row -->
      </div><!--End container -->
    </div><!--End st_v10_feature_area -->

    <footer id="contact" class="st_default_footer_area bg-ebony-clay st_subscribe_fotter st_section_padding">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 p-md-l-100 p-sm-l-15">
            <div class="st_footer_logo_warap">
              <%= image_tag "home/logo-white.png", alt: 'logo' %>
              <p>Comparte espacios comunes fácilmente.</p>
            </div>
          </div>
          <div class="col-lg-8 p-md-l-100 p-sm-l-15">
            <div class="row">
              <div class="col-lg-3 col-md-4 m-md-b-60 col-sm-6 offset-lg-4">
                <div class="st_fotter_heding_title">
                  <h3 class="text-blue-bell">Legal</h3>
                </div>
                <div class="st_fotter_menu text-st-white">
                  <ul>
                    <li>
                      <%= link_to 'Aviso Legal', legal_static_index_path %>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-5 col-md-4 m-md-b-60">
                <div class="st_fotter_heding_title">
                  <h3 class="text-blue-bell">Contacto</h3>
                </div>
                <div class="st_social_icon text-st-white">
                  <p class="text-st-primary"><%= Rails.application.credentials.dig(:support_email) %></p>
                </div>
              </div>
            </div><!--- End row -->
          </div>
        </div><!--- End row -->
      </div><!--- End container -->
    </footer><!--- End st_default_footer_area -->
    <!-- build:js -->
    <%= javascript_include_tag 'home', 'data-turbolinks-track': 'reload' %>
    <!-- End All Js -->
  </body>
</html>
<%= render 'cookies_eu/consent_banner', link: '/legal#cookies' %>